import type { RegisterFabricCapabilityDraft } from "@/schemas/fabric-capability";

/**
 * Seed inventory of Fabric item types, grounded in the current Microsoft
 * Fabric REST API documentation (see docs/FABRIC_API.md for sources and
 * verification date). This is intentionally not exhaustive of every
 * `ItemType` enum value Fabric documents — it covers the item types this
 * platform's blueprints actually provision, plus every type explicitly
 * named in the product brief. Additional types can be registered later via
 * FabricCapabilityRegistryService.registerCapability() without any UI
 * changes (see docs/FABRIC_API.md "Adding a new Fabric item type").
 *
 * Types Microsoft documents as list-only (no create API) are seeded with
 * createSupported: false and a note — the UI shows these as
 * "API provisioning not currently supported" rather than hiding them,
 * per the brief's explicit instruction to never fake support.
 */
export const fabricCapabilitySeed: RegisterFabricCapabilityDraft[] = [
  {
    itemType: "Workspace",
    displayName: "Workspace",
    category: "governance",
    description: "The Fabric workspace itself. Created via POST /v1/workspaces, not the generic items API.",
    apiPath: "workspaces",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    folderSupported: false,
    requiredScopes: ["Workspace.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/core/workspaces/create-workspace",
    parameters: [
      { key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 },
      { key: "capacityId", label: "Capacity", inputType: "resourcePicker", mode: "advanced", required: false, targetPath: "capacityId", sortOrder: 1 },
      { key: "domainId", label: "Domain", inputType: "resourcePicker", mode: "advanced", required: false, targetPath: "domainId", sortOrder: 2 },
    ],
  },
  {
    itemType: "Lakehouse",
    displayName: "Lakehouse",
    category: "storage",
    description: "OneLake-backed lakehouse with an automatically provisioned SQL Analytics Endpoint.",
    apiPath: "lakehouses",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: false,
    creationPayloadSupported: true,
    requiredScopes: ["Lakehouse.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/lakehouse/items",
    parameters: [
      { key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 },
      { key: "description", label: "Description", inputType: "textarea", mode: "basic", required: false, targetPath: "description", sortOrder: 1 },
      {
        key: "enableSchemas",
        label: "Enable schemas (preview)",
        inputType: "boolean",
        mode: "advanced",
        required: false,
        defaultValue: false,
        targetPath: "creationPayload.enableSchemas",
        sortOrder: 2,
      },
    ],
  },
  {
    itemType: "Warehouse",
    displayName: "Warehouse",
    category: "storage",
    description: "T-SQL data warehouse.",
    apiPath: "warehouses",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: false,
    creationPayloadSupported: true,
    requiredScopes: ["Warehouse.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/warehouse/items",
    parameters: [
      { key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 },
      { key: "description", label: "Description", inputType: "textarea", mode: "basic", required: false, targetPath: "description", sortOrder: 1 },
    ],
  },
  {
    itemType: "DataPipeline",
    displayName: "Data Pipeline",
    category: "pipeline",
    description: "Orchestration pipeline for copy/transform activities.",
    apiPath: "dataPipelines",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["DataPipeline.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/datapipeline/items",
    parameters: [
      { key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 },
      { key: "definition", label: "Pipeline definition (JSON)", inputType: "json", mode: "raw", required: false, targetPath: "definition", sortOrder: 1 },
    ],
  },
  {
    itemType: "CopyJob",
    displayName: "Copy Job",
    category: "pipeline",
    description: "Managed, schedule-driven data copy from a source connection to a Fabric destination.",
    apiPath: "copyJobs",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["CopyJob.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/copyjob/items",
    parameters: [
      { key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 },
      { key: "sourceConnection", label: "Source connection", inputType: "connectionPicker", mode: "basic", required: true, targetPath: "creationPayload.source", sortOrder: 1 },
    ],
  },
  {
    itemType: "Notebook",
    displayName: "Notebook",
    category: "compute",
    description: "Spark notebook, typically used for Silver-layer transformation logic.",
    apiPath: "notebooks",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["Notebook.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/notebook/items",
    parameters: [
      { key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 },
      { key: "definition", label: "Notebook definition (JSON)", inputType: "json", mode: "raw", required: false, targetPath: "definition", sortOrder: 1 },
    ],
  },
  {
    itemType: "Dataflow",
    displayName: "Dataflow Gen2",
    category: "pipeline",
    description: "Low-code Power Query based data transformation.",
    apiPath: "dataflows",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["Dataflow.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/dataflow/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "Environment",
    displayName: "Environment",
    category: "compute",
    description: "Spark compute/library environment shared across notebooks and Spark jobs.",
    apiPath: "environments",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["Environment.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/environment/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "SparkJobDefinition",
    displayName: "Spark Job Definition",
    category: "compute",
    description: "Standalone Spark batch job (non-notebook).",
    apiPath: "sparkJobDefinitions",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["SparkJobDefinition.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/sparkjobdefinition/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "SemanticModel",
    displayName: "Semantic Model",
    category: "analytics",
    description: "Power BI semantic (data) model over approved Gold data.",
    apiPath: "semanticModels",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["SemanticModel.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/semanticmodel/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "Report",
    displayName: "Power BI Report",
    category: "reporting",
    description: "Power BI report bound to a semantic model.",
    apiPath: "reports",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["Report.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/report/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "Eventhouse",
    displayName: "Eventhouse",
    category: "realtime",
    description: "Real-time analytics database container (KQL).",
    apiPath: "eventhouses",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    requiredScopes: ["Eventhouse.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/eventhouse/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "Eventstream",
    displayName: "Eventstream",
    category: "realtime",
    description: "Real-time event ingestion and routing.",
    apiPath: "eventstreams",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["Eventstream.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/eventstream/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "KQLDatabase",
    displayName: "KQL Database",
    category: "realtime",
    apiPath: "kqlDatabases",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    creationPayloadSupported: true,
    requiredScopes: ["KQLDatabase.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/kqldatabase/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "KQLQueryset",
    displayName: "KQL Queryset",
    category: "realtime",
    apiPath: "kqlQuerysets",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["KQLQueryset.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/kqlqueryset/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "KQLDashboard",
    displayName: "KQL Dashboard",
    category: "realtime",
    apiPath: "kqlDashboards",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["KQLDashboard.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/kqldashboard/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "GraphQLApi",
    displayName: "GraphQL API",
    category: "analytics",
    apiPath: "GraphQLApis",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    requiredScopes: ["Item.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/core/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  {
    itemType: "MirroredDatabase",
    displayName: "Mirrored Database",
    category: "storage",
    description: "Continuous mirroring from an external database (e.g. Snowflake, Azure SQL) into OneLake.",
    apiPath: "mirroredDatabases",
    createSupported: true,
    updateSupported: true,
    deleteSupported: true,
    definitionSupported: true,
    requiredScopes: ["MirroredDatabase.ReadWrite.All"],
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/mirroreddatabase/items",
    parameters: [{ key: "displayName", label: "Name", inputType: "text", mode: "basic", required: true, targetPath: "displayName", sortOrder: 0 }],
  },
  // --- Documented as list-only / no create API today. Seeded so the
  // registry (and therefore the UI) reflects reality rather than omitting
  // them silently — see brief section 53.
  {
    itemType: "Dashboard",
    displayName: "Dashboard",
    category: "reporting",
    description: "Classic Power BI dashboard.",
    apiPath: "dashboards",
    createSupported: false,
    updateSupported: false,
    deleteSupported: false,
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/articles/item-management/item-management-overview",
    parameters: [],
  },
  {
    itemType: "Datamart",
    displayName: "Datamart",
    category: "storage",
    createSupported: false,
    updateSupported: false,
    deleteSupported: false,
    apiPath: "datamarts",
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/articles/item-management/item-management-overview",
    parameters: [],
  },
  {
    itemType: "MirroredWarehouse",
    displayName: "Mirrored Warehouse",
    category: "storage",
    createSupported: false,
    updateSupported: false,
    deleteSupported: false,
    apiPath: "mirroredWarehouses",
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/articles/item-management/item-management-overview",
    parameters: [],
  },
  {
    itemType: "SQLEndpoint",
    displayName: "SQL Analytics Endpoint",
    category: "analytics",
    description: "Auto-provisioned alongside a Lakehouse; not independently created. Resolved via the parent Lakehouse's properties.sqlEndpointProperties.",
    createSupported: false,
    updateSupported: false,
    deleteSupported: false,
    apiPath: "sqlEndpoints",
    documentationUrl: "https://learn.microsoft.com/en-us/rest/api/fabric/lakehouse/items/get-lakehouse",
    parameters: [],
  },
];
